version: '2'

services:
  nginx:
    image: nginx:alpine
    links:
      - fpm
    ports:
      - "8080:80"
    volumes:
      - ./nginx/enabled:/etc/nginx/conf.d
      - ./nginx/snippets:/nginx/snippets
    volumes_from:
      - app

  fpm:
    image: php:7.0.8-fpm-alpine
    volumes_from:
      - app

  app:
    image: busybox
    volumes:
      - ./vhosts:/vhosts
